---
- name: Установка утилиты dnf-utils
  ansible.builtin.dnf:
    name: dnf-utils
    state: present

- name: Добавление официального репозитория Docker
  ansible.builtin.command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Установка базовых пакетов Docker
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Запуск и добавление Docker в автозагрузку
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Установка python3-pip
  ansible.builtin.dnf:
    name: python3-pip
    state: present

- name: Установка Python-библиотеки docker для Ansible через pip
  ansible.builtin.pip:
    name: docker
    executable: pip3
    state: present
