---
- name: Install exporters on all hosts
  hosts: webservers
  become: true
  roles:
    - role: exporters
      tags: [exporters, monitoring]

- name: Install monitoring stack (Prometheus + Grafana + Alertmanager)
  hosts: monitoring
  become: true
  vars_files:
    - ../inventory/group_vars/webservers_secret.yml
  roles:
    - role: prometheus
      tags: [prometheus, monitoring]
    - role: grafana
      tags: [grafana, monitoring]
    - role: alertmanager
      tags: [alertmanager, monitoring]
    - role: nginx_proxy
      tags: [nginx_proxy, monitoring]
