---
- name: Развертывание инфраструктуры Docker и Nginx
  hosts: webservers
  become: true

  roles:
    - role: docker_setup
      tags: [docker, setup]
    - role: nginx_deploy
      tags: [nginx, deploy]
